### ISSUE TITLE
Python Example Returns Error

### ISSUE THREAD

**Issue by grapedrank** [sparkfun/CCS811_Air_Quality_Breakout#2]
Hey Guys,

had the sensor working for a few days and had python write values to mysql but now the device has thrown errors, if i remove the power and bring the sensor back up and run the example code it returns this

CO2:  0 ppm, TVOC:  0  temp:  25.0
ERROR!

and if i try run the code again i get this

Traceback (most recent call last):
  File "CCS811_example.py", line 6, in <module>
    ccs =  Adafruit_CCS811()
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_CCS811/Adafruit_CCS811.py", line 92, in __init__
    raise Exception("Device returned an Error! Try removing and reapplying power to the device and running the code again.")
Exception: Device returned an Error! Try removing and reapplying power to the device and running the code again.

any ideas as to whats causing this?

**Comment by nseidle** [comment]
It looks as though there is no comm with the sensor at all. Any chance you have a logic analyzer? 

I would swap out sensors or controllers to isolate the problem.
