### ISSUE TITLE
setEnvironmentalData after readAlgorithmResults?

### ISSUE THREAD

**Issue by supersjimmie** [sparkfun/CCS811_Air_Quality_Breakout#3]
In the example BME280Compensated.ino, it first does the ```readAlgorithmResults``` and then the ```setEnvironmentalData```. Are you sure that's the correct order? Shouldn't we first compensate/set and then read??

**Comment by nseidle** [comment]
It's really not clear. The [CCS811 datasheet](https://cdn.sparkfun.com/datasheets/BreakoutBoards/CCS811_Programming_Guide.pdf) says:

> The CCS811 supports compensation for relative humidity and ambient temperature. The ENV_DATA registers can be updated with the temperature and humidity (TH) values on each cycle.

At what point in each cycle? It may not matter: the reading from the MOX sensor is going to change over many seconds and as the humidity and temperature change on similar, slow, whether the `setEnvironmentalData` comes before or after a `read` shouldn't effect the tVOC algorithm much. It will be corrected on the next read.
